### ISSUE TITLE
How to get raw audio files?

### ISSUE THREAD

**Issue by paraanggotaforum** [CMU-MultiComp-Lab/CMU-MultimodalSDK#3]
How do i get raw audio files, I've only gotten the processed ones, this is a somewhat difficult code to understand.

Raw is .wav

**Comment by lpmorency** [comment]
Raw data is not available, unfortunately. This is a constraint from YouTube. Instead, we share the link to the original URL.

**Comment by paraanggotaforum** [comment]
@lpmorency Hi, so if I read it correctly, CMU-MOSEI was from Youtube, and so you used to have the raw .wav data hosted in your site. But I suppose, now you can't give out the .wav/raw video audio data because of YouTube, so you can only give the processed data and/or the link? Is this correct? So if I want to get taw audio data, I have to scrape it video by video on YouTube?

Thank you

**Comment by lpmorency** [comment]
Yes, this is correct. We are slowly fading out support for the CMU Multimodal SDK (the main student developing it graduated). We are moving towards new code repositories. I would suggest looking at the Social-IQ 2.0 challenge which includes new baseline models and also some code for dataset processing:
https://cmu-multicomp-lab.github.io/social-iq-2.0/

**Comment by paraanggotaforum** [comment]
Ah, got it. Thank you very much for the clarification! I will look up the Social-IQ 2.0 Challenge.
