### ISSUE TITLE
Links and annotated transcriptions

### ISSUE THREAD

**Issue by mirix** [CMU-MultiComp-Lab/CMU-MultimodalSDK#4]
Hello,

I would be interested to train an audio-only model (or, perhaps, a bimodal audio-text one) using CMU-MOSEI data. 

I would be recomputing the audio embeddings.

So I would need only the links to the videos plus the timestamps and the annotated emotions per timestamp range (I can do the transcription if need be, but, if it is included, so much better).

How would I go about downloading this?

Thanks,

Ed

**Comment by mirix** [comment]
I have run the process_mosei script and ended up with several folders containing csd files.

I am guessing that I need final_aligned.

The question is, how can I go from those csd files to a csv file containing one column with the ids of the videos, other(s) with the sentence timestamps and another one with the emotion labels for each sentence?

**Comment by mirix** [comment]
Ok, perhaps I am getting to something:

```
import h5py
import numpy as np
import pandas as pd

filename = '/home/emoman/Downloads/mosei/CMU_MOSEI_Labels.csd'

hf = h5py.File(filename)

features = hf.get('All Labels/data/zv0Jl4TIQDc/features')
feat = np.array(features)
df_feat = pd.DataFrame(feat)
print(df_feat)

intervals = hf.get('All Labels/data/zv0Jl4TIQDc/intervals')
intval = np.array(intervals)
df_intval = pd.DataFrame(intval)
print(df_intval)
```

This gives:

```
          0         1    2         3    4    5    6
0  0.333333  0.666667  0.0  0.666667  0.0  0.0  0.0
1  1.000000  2.000000  0.0  0.000000  0.0  0.0  0.0
2  2.333333  2.666667  0.0  0.000000  0.0  0.0  0.0
        0       1
0  56.852  60.845
1  29.764  35.633
2  42.146  49.242
```

My interpretation is that video zv0Jl4TIQDc has three intervals annotated with the relative weights of Ekman's basic emotions.

Is that correct?

If that is the case, what would be the mapping of the emotions?

What is the highest possible value for a given emotion?

**Comment by mirix** [comment]
> 
> Each sentence is annotated for sentiment on a [-3,3]
> Likert scale of: [−3: highly negative, −2 negative,
> −1 weakly negative, 0 neutral, +1 weakly positive,
> +2 positive, +3 highly positive]. Ekman emotions
> (Ekman et al., 1980) of {happiness, sadness, anger,
> fear, disgust, surprise} are annotated on a [0,3] Lik-
> ert scale for presence of emotion x: [0: no evidence
> of x, 1: weakly x, 2: x, 3: highly x]. 
> 

So column zero is the Likert score and then the other columns would be, in this order, {happiness, sadness, anger, fear, disgust, surprise} ?

**Comment by mirix** [comment]
The issue with this interpretation is that segment 0 above would have been labelled with happiness and anger in similar amounts...

**Comment by mirix** [comment]
Or is it (Anger Disgust Fear Happy Sad Surprise) as in Table 3? 

Then it would be Anger and Fear, which is more consistent, but the sentiment would be slightly positive...

**Comment by mirix** [comment]
Checking the entries with the most negative and positive sentiment, it seems to be {happiness, sadness, anger, fear, disgust, surprise}

**Comment by lpmorency** [comment]
> Hello,
> 
> I would be interested to train an audio-only model (or, perhaps, a bimodal audio-text one) using CMU-MOSEI data.
> 
> I would be recomputing the audio embeddings.
> 
> So I would need only the links to the videos plus the timestamps and the annotated emotions per timestamp range (I can do the transcription if need be, but, if it is included, so much better).
> 
> How would I go about downloading this?
> 
> Thanks,
> 
> Ed

As mentioned in another thread, the timestamps and urls are available as part of the Social-IQ 2.0 challenge:
https://cmu-multicomp-lab.github.io/social-iq-2.0/

**Comment by mirix** [comment]
Thanks!

I have forked MOSEI and created a dataset with a narrower scope, I hope that is fine with everyone:

https://huggingface.co/datasets/mirix/messaih

**Comment by Vedaad-Shakib** [comment]
@mirix Thanks for your work on this! I noticed a comment on the HuggingFace page that MESSAIH is half the size of MOSEI. Can you provide some info on why some files are missing?

**Comment by mirix** [comment]
> @mirix Thanks for your work on this! I noticed a comment on the HuggingFace page that MESSAIH is half the size of MOSEI. Can you provide some info on why some files are missing?

Two reasons:

1. Messaih only has audio (not video).
2. Over 30% of the videos of the original dataset were no longer available from one reason or another.

Our results with MESSAIH for voice emotion analysis were not encouraging.

I guess that the MOSEI annotations are largely based on visual cues.

In addition, the emotions displayed by the social media influencers are overwhelmingly "positive" and, rather often, probably inauthentic.

**Comment by Vedaad-Shakib** [comment]
Gotcha, thanks for the details :-) Out of curiosity, what datasets did you find work the best for voice emotion analysis? I'm working on conditioning text-to-speech to output emotional speech, and I've found that small but very high quality datasets tend to work much better than large & potentially noisy datasets or datasets collected in the wild.

This is a great resource if you haven't seen it yet: https://github.com/SuperKogito/SER-datasets
