### ISSUE TITLE
Files do not exist

### ISSUE THREAD

**Issue by hcliucs** [CMU-MultiComp-Lab/CMU-MultimodalSDK#5]
Hi, 

I'm going to download .csd files using the following codes:
```python
md.mmdataset(DATASET.highlevel, DATA_PATH)

md.mmdataset(DATASET.raw, DATA_PATH)

md.mmdataset(DATASET.labels, DATA_PATH)
```

However, it reports error as like:
> [2023-08-29 05:32:28.669] | Error   | URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd does not exist
> [2023-08-29 05:32:29.693] | Error   | URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWords.csd does not exist
> [2023-08-29 05:32:30.738] | Error   | URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/labels/CMU_MOSI_Opinion_Labels.csd does not exist

At the same time, I cannot access the URL http://immortal.multicomp.cs.cmu.edu/CMU-MOSI. It shows that I have no permission. How should I obtain these .csd files?

Thanks!

**Comment by cenjinglun** [comment]
I have encountered the same issue. Have you resolved it?

**Comment by helemanc** [comment]
Any updates?

**Comment by abwilf** [comment]
Hello! The files should be back up on http://immortal.multicomp.cs.cmu.edu/. Please let us know if you have any more issues.

**Comment by cenjinglun** [comment]
Thanks!
