### ISSUE TITLE
Question regarding the MOSEI test set

### ISSUE THREAD

**Issue by hugodecasta** [CMU-MultiComp-Lab/CMU-MultimodalSDK#9]
I am currently using the MOSEI dataset as part of a Multimodal project.
I need to evaluate my methods and compare to SOA but i cannot find a filtered test subset that would be general and reflect challenging cases.

Did i miss something or is there no general test subset for the MOSEI dataset ?

Shouldn't there be one since many papers are proposing new methods and comparing them using the MOSEI DS ?

**Comment by arin688** [comment]
can anyone please give me the Mosei datasets

**Comment by hugodecasta** [comment]
> can anyone please give me the Mosei datasets

You can download it using this repository's scripts.
Or if you prefer to do it manually, the URLs are inside this reposity's files

**Comment by arin688** [comment]
Thank you for your response.

**Comment by abwilf** [comment]
Closing for now – if you have anyfurther questions please reach out!
